spring.application.name = learn-spring-boot
spring.mvc.format.date = yyyy-MM-dd
#logging.level.org.springframework = debug
#spring.profiles.active = dev

#set the logging level on a specific package instead of the whole application
logging.level.com.outlook.philiphyw.todomanager = debug

chat-service.url = http://localhost:8081
chat-service.username = localUser
chat-service.key = local1234

#set actuator exposure level
management.endpoints.web.exposure.include=*

#h2 database
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:todomanager

#jpa
spring.jpa.show-sql=false

#jsp
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp