spring.application.name=learn-spring-boot
#spring.profiles.active = dev

chat-service.url = http://localhost:8081
chat-service.username = localUser
chat-service.key = local1234

#set actuator exposure level
management.endpoints.web.exposure.include=*

#h2 database
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb